name: Build Electron App

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build distributables
        run: npm run dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: dist/*

      - name: Publish to Snap Store
        if: false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Add the command for publishing here, e.g.,
          echo "Publishing to Snap Store..."
